version: '2'
services:
  dev:
    build: .
    ports:
     - "1337:8080"
    volumes:
     - .:/usr/src/app
  staging:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
  production:
    build: .
    ports:
     - "80:8080"
    volumes:
     - .:/usr/src/app